Bloggie.web/Models/Domain/BlogPost.cs
namespace Bloggie.web.Models.Domain
{
    public class BlogPost
    {
        public Guid Id { get; set; }
        public string Header { get; set; }
        public string PageTitle { get; set; }
        public string PageContent { get; set; }
        public string ShortDescription { get; set; }
        public string FeaturedImageUrl { get; set; }
        public string UrlHandle { get; set; }
        public DateTime PublishedDate { get; set; }
        public string Author { get; set; }
        public bool Visible { get; set; }
        public ICollection<Tag> Tags { get; set; }  
    }
}

Bloggie.web/Models/Domain/Tag.cs
namespace Bloggie.web.Models.Domain
{
    public class Tag
    {
        public Guid Id { get; set; }
        public string Name { get; set; }
        public string DisplayName { get; set; }
        public ICollection<BlogPost> Posts { get; set; }
    }
}

Bloggie.web/Models/ErrorViewModel.cs
namespace Bloggie.web.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Bloggie.web/Models/ViewModel/AddTagRequest.cs
using System.ComponentModel.DataAnnotations;

namespace Bloggie.web.Models.ViewModel
{
    public class AddTagRequest
    {
        [Required] 
        public string Name { get; set; }
        [Required]       
        public string DisplayName { get; set; }
    }
}

Bloggie.web/Models/ViewModel/EditTagRequest.cs
namespace Bloggie.web.Models.ViewModel
{
    public class EditTagRequest
    {
        public Guid Id { get; set; }
        public string Name { get; set; }
        public string DisplayName { get; set; }
    }
}

Bloggie.web/Controllers/AdminTagController.cs
using Bloggie.web.Data;
using Bloggie.web.Models.Domain;
using Bloggie.web.Models.ViewModel;
using Bloggie.web.Repository.Interface;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Bloggie.web.Controllers
{
    public class AdminTagController : Controller
    {
        private readonly ITagRepository repo;

        public AdminTagController(ITagRepository repo)
        {
            this.repo = repo;
        }
        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Add(AddTagRequest addTagRequest)
        {
            //var name = Request.Form["name"];
            //var displayName = Request.Form["displayName"];

            // mapping AddTagRequest to domain model
            var tag = new Tag()
            {
                Name = addTagRequest.Name,
                DisplayName = addTagRequest.DisplayName,
            };

              await repo.AddTagAsync(tag);

            return RedirectToAction("List");
        }

        [HttpGet]
        public async Task<IActionResult> List()
        {
            var tags = await repo.GetAllAsync();

            return View(tags);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(Guid id)
        {
            var tag = await repo.GetTagAsync(id);
            if (tag != null) {

                var editTagRequest = new EditTagRequest()
                {
                    Id = id,
                    Name = tag.Name,
                    DisplayName = tag.DisplayName,
                };

                return View(editTagRequest);
            }
            return View(null);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(EditTagRequest editTagRequest)
        {
            var tag = new Tag()
            {
                Name = editTagRequest.Name,
                DisplayName = editTagRequest.DisplayName,
                Id = editTagRequest.Id
            };

            var existingTag = await repo.UpdateTagAsync(tag);

            if (existingTag != null)
            {
                return RedirectToAction("List");
            }

            return View(editTagRequest);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(EditTagRequest editTagRequest) 
        {
            var tag = await repo.DeleteTagAsync(editTagRequest.Id);
            if (tag != null) { 

                //show success notification
                return RedirectToAction("List");
            }

            //show error notification
            return RedirectToAction("Edit", editTagRequest);
        }
    }
}

Bloggie.web/Controllers/HomeController.cs
using System.Diagnostics;
using Bloggie.web.Models;
using Microsoft.AspNetCore.Mvc;

namespace Bloggie.web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Bloggie.web/Views/AdminTag/Add.cshtml
@model Bloggie.web.Models.ViewModel.AddTagRequest

<div class="bg-secondary bg-opacity-10 py-2">
	<div class="container">
		<h1>
			Add New Tag - Admin Functionality
		</h1>
	</div>
</div>
<div class="container py-5">
	<form method="post">
		<div class="mb-3">
			<label class="form-label">Name</label>
			<input type="text" class="form-control" id="name" asp-for="Name"/>
		</div>
		<div class="mb-3">
			<label class="form-label">Display Name</label>
			<input type="text" class="form-control" id="displayName" asp-for="DisplayName" />
		</div>
		<div class="mb-3">
			<button type="submit" class="btn btn-dark">Save</button>
		</div>
	</form>
</div>

Bloggie.web/Views/AdminTag/Edit.cshtml
@model Bloggie.web.Models.ViewModel.EditTagRequest

<div class="bg-secondary bg-opacity-10 py-2">
	<div class="container">
		<h1>
			Edit Tag - Admin Functionality
		</h1>
	</div>
</div>

<div class="container py-5">
	<form method="post">

		<div class="mb-3">
			<label class="form-label">Id</label>
			<input type="text" id="id" class="form-control" asp-for="Id" readonly />
		</div>

		<div class="mb-3">
			<label class="form-label">Name</label>
			<input type="text" id="name" class="form-control" asp-for="Name" />
		</div>

		<div class="mb-3">
			<label class="form-label">Display Name</label>
			<input type="text" id="displayName" class="form-control" asp-for="DisplayName" />
		</div>

		<div class="mb-3">
			<div class="d-flex">
				<button class="btn btn-dark" type="submit">Upadte</button>
				<button class="btn btn-danger" type="submit" asp-area=""
						asp-controller="AdminTag" asp-action="Delete">
					Delete
				</button>
			</div>
		</div>
	</form>
</div>

Bloggie.web/Views/AdminTag/List.cshtml
@model List<Bloggie.web.Models.Domain.Tag>

<div class="bg-secondary bg-opacity-10 py-2">
	<div class="container">
		<h1>
			Add New Tag - Admin Functionality
		</h1>
	</div>
</div>

<div class="container py-5">
	@if(Model != null && Model.Any())
	{
		<table class="table">
			<thead></thead>
			<tr>
				<th>ID</th>
				<th>Name</th>
				<th>Display Name</th>
				<th> </th>
			</tr>
			<tbody>
				@foreach(var tag in Model)
				{
					<tr>
						<td>@tag.Id</td>
						<td>@tag.Name</td>
						<td>@tag.DisplayName</td>
						<td>
							<a asp-area="" 
							asp-controller="AdminTag"
							asp-action="Edit"
							asp-route-id="@tag.Id">
							Edit</a>
						</td>
					</tr>
				}
			</tbody>
		</table>
	}
	else
	{
		<h1>Sorry, No Tags were found!</h1>
	}

</div>

Bloggie.web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Bloggie.web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] - Bloggie.web</title>
	<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
	<link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
	<link rel="stylesheet" href="~/Bloggie.web.styles.css" asp-append-version="true" />
</head>
<body>
	<header>
		<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow">
			<div class="container-fluid">
				<a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Bloggie.web</a>
				<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
						aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
				<div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
					<ul class="navbar-nav flex-grow-1">
						<li class="nav-item">
							<a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
						</li>
						<li class="nav-item dropdown">
							<a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
								Admin
							</a>
							<ul class="dropdown-menu">
								<li><a class="dropdown-item" asp-area=""asp-controller="AdminTag"
								asp-action="Add">Add Tag</a></li>
								<li>
									<a class="dropdown-item" asp-area="" asp-controller="AdminTag"
									   asp-action="List">Show all Tags</a>
								</li>
							</ul>
						</li>
					</ul>
				</div>
			</div>
		</nav>
	</header>
	<div class="container">
		<main role="main" class="pb-3">
			@RenderBody()
		</main>
	</div>

	<footer class="border-top footer text-muted">
		<div class="container">
			&copy; 2025 - Bloggie.web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
		</div>
	</footer>
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
	<script src="~/js/site.js" asp-append-version="true"></script>
	@await RenderSectionAsync("Scripts", required: false)
</body>
</html>